language: ruby
rvm:
 - 2.2
 - jruby

sudo: required
services:
	-  docker

before_install:
	- docker build -t aheredia993/docker-react -f Dockerfile.dev .
	
script:
	- docker run -e CI=true aheredia993/docker-react npm run test
    

    